/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>

int main(void)
{

	uint8_t estatura = 160;
	bool puedeEntrar;
	(void)puedeEntrar;

	if(estatura < 150){
		puedeEntrar = false;
	}else{
		puedeEntrar = true;
	}

    uint32_t dineroEnLaCuenta = 3000000;
    bool tieneCarro = false;
    bool leAceptoLaSalida;

    if(dineroEnLaCuenta > 1500000 && dineroEnLaCuenta > 500000){
    	if(tieneCarro){
    		leAceptoLaSalida = true;
    	}else{
    		leAceptoLaSalida = false;
    	}

    }else if(dineroEnLaCuenta < 150000){
    	leAceptoLaSalida = false;
    }else if(dineroEnLaCuenta > 500000){
    	leAceptoLaSalida = true;
    }

    for(uint32_t i = 0; i < 10; i++){
    	uint32_t tablaDel7 = 7*i;
    }

    for(uint16_t horas = 0; horas < 24; horas ++){
    	for(uint16_t minutos = 0; minutos < 60; minutos ++){
    		for (uint16_t segundos = 0; segundos < 60; segundos ++){
    			for (uint16_t contador = 0; contador < 1200000; contador ++){
    				NOP();
    			}
    		}
    	}
    }

    /* Loop forever */
	while(1){
	}
}

